_wandb:
    value:
        cli_version: 0.25.1
        e:
            84r0cdx64o5gwqbf9y2d7sody69yvxiv:
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "3935709487104"
                        used: "597587685376"
                email: da632@njit.edu
                executable: /home/johnsmith/Desktop/njit/workspaces/torchvision-frcnn-hpo/.venv/bin/python3
                gpu: NVIDIA GeForce RTX 3080 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 7424
                      memoryTotal: "17179869184"
                      name: NVIDIA GeForce RTX 3080 Ti Laptop GPU
                      uuid: GPU-3815f5da-e0c1-6fbc-07c2-aa46ef732d33
                host: ravensNest
                memory:
                    total: "67258839040"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: <python with no main file>
                python: CPython 3.12.3
                root: /home/johnsmith/Desktop/njit/workspaces/torchvision-frcnn-hpo
                startedAt: "2026-03-13T19:25:38.131288Z"
                writerId: 84r0cdx64o5gwqbf9y2d7sody69yvxiv
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 35
                - 41
                - 49
            "2":
                - 1
                - 35
                - 41
                - 49
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.25.1
            "8":
                - 1
            "10":
                - 20
            "12": 0.25.1
            "13": linux-x86_64
box_nms_thresh:
    value: 0.5895791591945723
detections_per_img:
    value: 249
score_thresh:
    value: 0.06890786878770465
stage:
    value: stage4_post
