_wandb:
    value:
        cli_version: 0.25.1
        e:
            t2n7lqmqfpe8lx4lczutm45f2b7197ds:
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "3935709487104"
                        used: "597761826816"
                email: da632@njit.edu
                executable: /home/johnsmith/Desktop/njit/workspaces/torchvision-frcnn-hpo/.venv/bin/python3
                gpu: NVIDIA GeForce RTX 3080 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 7424
                      memoryTotal: "17179869184"
                      name: NVIDIA GeForce RTX 3080 Ti Laptop GPU
                      uuid: GPU-3815f5da-e0c1-6fbc-07c2-aa46ef732d33
                host: ravensNest
                memory:
                    total: "67258839040"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: <python with no main file>
                python: CPython 3.12.3
                root: /home/johnsmith/Desktop/njit/workspaces/torchvision-frcnn-hpo
                startedAt: "2026-03-13T23:15:11.883186Z"
                writerId: t2n7lqmqfpe8lx4lczutm45f2b7197ds
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 35
                - 41
                - 49
            "2":
                - 1
                - 35
                - 41
                - 49
            "3":
                - 2
                - 3
                - 13
                - 16
            "4": 3.12.3
            "5": 0.25.1
            "8":
                - 1
            "10":
                - 20
            "12": 0.25.1
            "13": linux-x86_64
box_loss_weight:
    value: 1.86668360234047
box_nms_thresh:
    value: 0.5895791591945723
cls_loss_weight:
    value: 1.4996969788547254
detections_per_img:
    value: 249
epochs:
    value: 3
final_epochs:
    value: 12
final_seed:
    value: 22
grad_clip_norm:
    value: 2.5919641029876854
lr:
    value: 6.829352954261399e-05
momentum:
    value: 0.8609901026988318
roi_batch_size_per_image:
    value: 386
roi_positive_fraction:
    value: 0.17617821027852887
rpn_batch_size_per_image:
    value: 317
rpn_bg_iou_thresh:
    value: 0.28100948788550334
rpn_fg_iou_thresh:
    value: 0.6049307638099946
rpn_nms_thresh:
    value: 0.6476916249037943
rpn_positive_fraction:
    value: 0.7364361649344031
rpn_post_nms_topk:
    value: 1642
rpn_pre_nms_topk:
    value: 1176
score_thresh:
    value: 0.06890786878770465
seed:
    value: 2621
weight_decay:
    value: 6.87491841689458e-05
